import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';
import prettier from 'eslint-config-prettier';

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Must come last: turns off every rule Prettier already handles.
  prettier,
  globalIgnores([
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    'playwright-report/**',
    // Generated by the Serwist CLI during `npm run build`. It is bundled,
    // minified output; linting it reports on esbuild's choices, not ours.
    'public/sw.js',
    'public/swe-worker-*.js',
    // Crawled copy of the legacy site and the migration mapping (see .gitignore).
    'migration/.cache/**',
  ]),
]);

export default eslintConfig;
