import type { NextConfig } from 'next';
import createNextIntlPlugin from 'next-intl/plugin';

import legacyRedirects from './lib/legacy-redirects.json' with { type: 'json' };

const withNextIntl = createNextIntlPlugin('./i18n/request.ts');

const nextConfig: NextConfig = {
  /**
   * The airport self-hosts. `standalone` emits a self-contained server bundle
   * that runs under plain Node, with no platform-specific runtime (plan §3.4).
   * Nothing in this project may depend on Vercel.
   */
  output: 'standalone',

  /** Don't advertise the framework version. */
  poweredByHeader: false,

  /**
   * Legacy URL redirects (plan §8 step 6).
   *
   * Generated by `npm run migrate:generate` from the reconciliation mapping,
   * and committed so the build needs no crawl. Every legacy URL that returned
   * 200 has an entry, including pages that were dropped — those point at the
   * section they would have belonged to rather than a 404 a visitor cannot act
   * on.
   *
   * The arrivals/departures pair is deliberately not slug-preserving: the
   * legacy `/incoming-flights/` page listed departures and `/outbound-flights/`
   * listed arrivals, so each redirects to the board view its content actually
   * described, not the one its slug claimed.
   */
  async redirects() {
    return legacyRedirects;
  },
};

export default withNextIntl(nextConfig);
