/**
 * Stage 8, step 2 — reconcile the inventory against the new IA (plan §8).
 *
 *   npm run migrate:reconcile
 *
 * Joins the hand-authored decisions in `mapping.mts` against the crawled
 * inventory and writes the review document. Exits non-zero if any legacy page
 * is unaccounted for, which is Stage 8's exit criterion expressed as an
 * assertion rather than a promise: "all 74 RU pages accounted for as migrate /
 * merge / drop-with-reason".
 *
 * Generates no MDX. The plan requires this table to be reviewed first.
 */
import fs from 'node:fs';
import path from 'node:path';

import { loadMapping } from './load-mapping.mts';
import type { Decision } from './mapping-types.mts';

const { MAPPING } = await loadMapping();

interface InventoryRecord {
  url: string;
  slug: string;
  locale: 'ru' | 'en' | 'kz';
  type: string;
  status: number;
  title: string;
  heading: string;
  description: string;
  words: number;
  wordsRaw: number;
  images: string[];
  iframes: string[];
  tables: number;
  files: string[];
}

const OUT_DIR = path.resolve(process.cwd(), 'migration');
const inventory: InventoryRecord[] = JSON.parse(
  fs.readFileSync(path.join(OUT_DIR, 'inventory.json'), 'utf8')
);

const ruPages = inventory.filter((r) => r.locale === 'ru' && r.type === 'page');
const bySlug = new Map<string, InventoryRecord[]>();
for (const record of inventory.filter((r) => r.type === 'page')) {
  if (!bySlug.has(record.slug)) bySlug.set(record.slug, []);
  bySlug.get(record.slug)!.push(record);
}

// ---------------------------------------------------------------------------
// Validation — the exit criterion
// ---------------------------------------------------------------------------

const problems: string[] = [];

for (const page of ruPages) {
  if (!(page.slug in MAPPING)) {
    problems.push(`unmapped: ${page.slug}  ("${page.heading}", ${page.words}w)`);
  }
}

for (const slug of Object.keys(MAPPING)) {
  if (!ruPages.some((p) => p.slug === slug)) {
    problems.push(`mapping refers to a slug that is not a RU page: ${slug}`);
  }
}

const paths = new Map<string, string>();
for (const [slug, decision] of Object.entries(MAPPING)) {
  if (decision.action === 'migrate') {
    const clash = paths.get(decision.path);
    if (clash) problems.push(`two pages claim ${decision.path}: ${clash} and ${slug}`);
    paths.set(decision.path, slug);
  }
  if (decision.action === 'merge' && !(decision.into in MAPPING)) {
    problems.push(`${slug} merges into ${decision.into}, which has no decision`);
  }
}

if (problems.length > 0) {
  console.error(`\n${problems.length} problem(s) with the mapping:\n`);
  for (const problem of problems) console.error(`  ${problem}`);
  console.error('\nEvery legacy page needs exactly one decision before MDX generation.\n');
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Report
// ---------------------------------------------------------------------------

const counts = { migrate: 0, merge: 0, replace: 0, drop: 0 };
for (const decision of Object.values(MAPPING)) counts[decision.action] += 1;

function target(decision: Decision): string {
  switch (decision.action) {
    case 'migrate':
      return decision.path;
    case 'merge':
      return `→ ${decision.into}`;
    case 'replace':
      return decision.by;
    case 'drop':
      return '—';
  }
}

function why(decision: Decision): string {
  return decision.action === 'drop' ? decision.reason : (decision.note ?? '');
}

const rows = ruPages
  .map((page) => ({ page, decision: MAPPING[page.slug]! }))
  .sort(
    (a, b) =>
      a.decision.action.localeCompare(b.decision.action) ||
      target(a.decision).localeCompare(target(b.decision))
  );

const localesFor = (slug: string) => new Set((bySlug.get(slug) ?? []).map((r) => r.locale));

/** Pages that survive migration and are missing a translation. */
const gaps = rows
  .filter(({ decision }) => decision.action === 'migrate')
  .map(({ page, decision }) => {
    const has = localesFor(page.slug);
    return {
      slug: page.slug,
      path: decision.action === 'migrate' ? decision.path : '',
      heading: page.heading,
      missing: (['en', 'kz'] as const).filter((l) => !has.has(l)),
    };
  })
  .filter((entry) => entry.missing.length > 0);

const escape = (value: string) => value.replace(/\|/g, '\\|');

const md = `# Stage 8 — IA reconciliation

Generated by \`npm run migrate:reconcile\`. Do not edit by hand; edit
\`scripts/migrate/mapping.ts\` and regenerate.

**This table must be reviewed before any MDX is generated** (plan §8 step 2).
It is the step where the project either fixes the information architecture or
reproduces the old mess in a new stack.

## Summary

| | Count |
| --- | --- |
| Legacy RU pages | ${ruPages.length} |
| → migrate | ${counts.migrate} |
| → merge into another page | ${counts.merge} |
| → replaced by a built feature | ${counts.replace} |
| → dropped with reason | ${counts.drop} |
| Unaccounted for | **0** |

Crawl totals: ${inventory.length} URLs (${inventory.filter((r) => r.locale === 'ru').length} RU,
${inventory.filter((r) => r.locale === 'en').length} EN, ${inventory.filter((r) => r.locale === 'kz').length} KZ),
median ${[...inventory].sort((a, b) => a.words - b.words)[Math.floor(inventory.length / 2)]?.words ?? 0} words,
${inventory.filter((r) => r.words < 25).length} URLs under 25 words.

## Decisions

| Legacy slug | Heading on the page | Words | Action | Target | Note |
| --- | --- | ---: | --- | --- | --- |
${rows
  .map(
    ({ page, decision }) =>
      `| \`${escape(page.slug)}\` | ${escape(page.heading)} | ${page.words} | ${decision.action} | ${escape(target(decision))} | ${escape(why(decision))} |`
  )
  .join('\n')}

## Translation gaps (step 4)

${gaps.length} migrated pages are missing at least one translation.

| Page | Missing |
| --- | --- |
${gaps.map((g) => `| \`${escape(g.path)}\` (${escape(g.heading)}) | ${g.missing.join(', ')} |`).join('\n')}

## Attachments to re-host

| Legacy page | Files |
| --- | ---: |
${inventory
  .filter((r) => r.files.length > 0)
  .sort((a, b) => b.files.length - a.files.length)
  .map((r) => `| \`${escape(r.slug)}\` (${r.locale}) | ${r.files.length} |`)
  .join('\n')}
`;

fs.writeFileSync(path.join(OUT_DIR, 'reconciliation.md'), md, 'utf8');

const csvEscape = (value: string | number) => `"${String(value).replace(/"/g, '""')}"`;
const csv = [
  'slug,heading,title,words,action,target,note,locales',
  ...rows.map(({ page, decision }) =>
    [
      page.slug,
      page.heading,
      page.title,
      page.words,
      decision.action,
      target(decision),
      why(decision),
      [...localesFor(page.slug)].sort().join(' '),
    ]
      .map(csvEscape)
      .join(',')
  ),
].join('\n');
fs.writeFileSync(path.join(OUT_DIR, 'reconciliation.csv'), `${csv}\n`, 'utf8');

console.log(`\nAll ${ruPages.length} RU pages accounted for.\n`);
console.log(
  `  migrate ${counts.migrate}   merge ${counts.merge}   replace ${counts.replace}   drop ${counts.drop}`
);
console.log(`  ${gaps.length} migrated pages missing a translation`);
console.log(`\nWrote migration/reconciliation.md and migration/reconciliation.csv\n`);
