import { describe, expect, it } from 'vitest';

import redirects from '@/lib/legacy-redirects.json';

/**
 * The legacy redirect map (plan §8 step 6).
 *
 * Generated by `npm run migrate:generate` and committed, so these assertions
 * guard a file a person can edit by hand — and the one rule that is easy to get
 * wrong by "fixing" it is the arrivals/departures swap.
 */

interface Redirect {
  source: string;
  destination: string;
  permanent: boolean;
}

const map = redirects as Redirect[];

describe('shape', () => {
  it('covers the legacy site at a plausible scale', () => {
    // The sitemap holds ~249 URLs; a map that collapsed to a handful would mean
    // the generator silently stopped emitting.
    expect(map.length).toBeGreaterThan(200);
  });

  it('every entry is a permanent redirect between two absolute paths', () => {
    for (const entry of map) {
      expect(entry.source.startsWith('/'), entry.source).toBe(true);
      expect(entry.destination.startsWith('/'), entry.destination).toBe(true);
      expect(entry.permanent).toBe(true);
    }
  });

  it('has no duplicate sources', () => {
    const seen = new Map<string, string>();
    const duplicates: string[] = [];
    for (const entry of map) {
      if (seen.has(entry.source)) duplicates.push(entry.source);
      seen.set(entry.source, entry.destination);
    }
    expect(duplicates).toEqual([]);
  });

  it('never redirects a path to itself', () => {
    // Next refuses to start on a self-referential redirect, so this would take
    // the whole site down rather than break one URL.
    expect(map.filter((entry) => entry.source === entry.destination)).toEqual([]);
  });

  it('never redirects into a locale that does not exist', () => {
    const bad = map.filter((entry) => /^\/(kk|de|fr)\//.test(entry.destination));
    // The Kazakh URL prefix is /kz even though the locale code is kk.
    expect(bad).toEqual([]);
  });

  it('has no trailing slash on any source', () => {
    // Every legacy WordPress URL ends in a slash, but Next strips it before
    // consulting this table, so a rule keyed on `/wifi/` is never reached and
    // the visitor gets a 404. This was a real bug, caught by loading the page.
    const slashed = map.filter((entry) => entry.source !== '/' && entry.source.endsWith('/'));
    expect(slashed).toEqual([]);
  });
});

describe('the arrivals/departures swap', () => {
  /**
   * The legacy pages are mislabelled: `/incoming-flights/` is headed "Вылеты"
   * and lists departures, `/outbound-flights/` is headed "Прилеты" and lists
   * arrivals (plan §8 step 6). The redirects follow the content, not the slug.
   *
   * Anyone "correcting" these to match the slugs would silently send every
   * arriving passenger to the departures board.
   */
  const destinationOf = (source: string) =>
    map.find((entry) => entry.source === source)?.destination;

  it('sends /incoming-flights/ to departures, matching what the page showed', () => {
    expect(destinationOf('/incoming-flights')).toBe('/flights?kind=departures');
  });

  it('sends /outbound-flights/ to arrivals, matching what the page showed', () => {
    expect(destinationOf('/outbound-flights')).toBe('/flights?kind=arrivals');
  });

  it('applies the same correction in every locale', () => {
    // The Kazakh URL prefix is /kz even though the locale code is kk.
    expect(destinationOf('/en/incoming-flights')).toBe('/en/flights?kind=departures');
    expect(destinationOf('/kz/incoming-flights')).toBe('/kz/flights?kind=departures');
    expect(destinationOf('/en/outbound-flights')).toBe('/en/flights?kind=arrivals');
    expect(destinationOf('/kz/outbound-flights')).toBe('/kz/flights?kind=arrivals');
  });
});

describe('coverage of pages that no longer exist', () => {
  const destinationOf = (source: string) =>
    map.find((entry) => entry.source === source)?.destination;

  it('sends dropped commerce pages somewhere useful rather than to a 404', () => {
    for (const source of ['/cart', '/checkout', '/my-account', '/shop']) {
      expect(destinationOf(source), source).toBeDefined();
    }
  });

  it('keeps the replaced feature pages pointing at their replacements', () => {
    expect(destinationOf('/feedback')).toBe('/contacts');
    expect(destinationOf('/airport-map')).toBe('/contacts');
    expect(destinationOf('/frequently-asked-questions')).toBe('/faq');
    expect(destinationOf('/airport-news')).toBe('/news');
  });

  it('redirects news posts to their new slugs', () => {
    const newsRedirects = map.filter((entry) => entry.destination.includes('/news/'));
    expect(newsRedirects.length).toBeGreaterThan(20);
  });
});
