import fs from 'node:fs';
import path from 'node:path';

import { getActiveSchedule } from '@/lib/flights/queries';
import { env } from '@/lib/env';

/**
 * Serves the original weekly workbook (spec §6.4).
 *
 * The legacy site's only schedule feature was this download, so it is kept.
 *
 * The file is streamed through a route handler rather than served statically
 * because it lives in DATA_DIR, outside the public directory — uploaded files
 * must never sit in a web root where an unexpected extension could be served
 * as something executable.
 */

// Touches the filesystem and SQLite; never the Edge runtime (plan §3.4).
export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export async function GET() {
  const schedule = getActiveSchedule();
  if (!schedule) {
    return new Response('No schedule has been published yet.', {
      status: 404,
      headers: { 'content-type': 'text/plain; charset=utf-8' },
    });
  }

  /**
   * `storedPath` is generated by the importer, never taken from the uploaded
   * filename — but it is still resolved and re-checked against DATA_DIR here.
   * A path escaping the data directory should be impossible; if it ever
   * happens, this refuses rather than serving an arbitrary file.
   */
  const absolute = path.resolve(env.paths.dataDir, schedule.storedPath);
  if (!absolute.startsWith(path.resolve(env.paths.dataDir) + path.sep)) {
    return new Response('Not found.', { status: 404 });
  }

  if (!fs.existsSync(absolute)) {
    return new Response('The schedule file is missing on disk.', {
      status: 404,
      headers: { 'content-type': 'text/plain; charset=utf-8' },
    });
  }

  const file = fs.readFileSync(absolute);
  const stat = fs.statSync(absolute);

  // Offer the airport's own filename for saving, stripped of anything that
  // could break the header or traverse a path on the way out.
  const safeName =
    schedule.originalFilename.replace(/[^\w.\-()\s]/g, '_').slice(0, 100) || 'schedule.xlsx';

  return new Response(new Uint8Array(file), {
    headers: {
      'content-type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'content-disposition': `attachment; filename="${safeName}"`,
      'content-length': String(stat.size),
      'cache-control': 'public, max-age=300',
      'x-content-type-options': 'nosniff',
    },
  });
}
